language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -r requirements/test.txt --use-mirrors"
script:
  - export DJANGO_SETTINGS_MODULE=grandma.settings.test
  - python grandma/manage.py test
notifications:
  - on_success: change
  - on_failure: change
